# Generated by Django 5.2.15 on 2026-06-05 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('total_slots', models.PositiveIntegerField(default=10)),
                ('available_slots', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('full', 'Full'), ('maintenance', 'Maintenance')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lockers', to='branches.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
